sources:
- database: TEST_DB
  name: jaffle_shop_raw
  schema: jaffle_shop
  tables:
  - name: customers
  - name: orders
- database: TEST_DB
  name: stripe_raw
  schema: stripe
  tables:
  - name: payment
version: 2
