sources:
- database: RAW_JAFFLE
  name: jaffle_shop_raw
  schema: jaffle_raw_schema
  tables:
  - name: customers
  - name: orders
- database: RAW_JAFFLE
  name: stripe_raw
  schema: stripe
  tables:
  - name: payment
version: 2
